[package]
name = "indexander-cli"
description = "Command line interface to the indexander search engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "indexander"
path = "src/main.rs"

[dependencies]
indexander-core.workspace = true
indexander-index.workspace = true

[lints]
workspace = true
