[package]
name = "indexander-cli"
description = "Command line interface to the indexander search engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "indexander"
path = "src/main.rs"

[dependencies]
indexander-core.workspace = true
indexander-crawl = { version = "0.1.0", path = "../crawl" }
indexander-index.workspace = true
indexander-rank = { version = "0.1.0", path = "../rank" }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
url = "2.5.8"

[lints]
workspace = true
