[package]
name = "indexander-rank"
description = "Link graph and PageRank"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
indexander-core.workspace = true

[lints]
workspace = true
